-- CreateTable
CREATE TABLE "Ferrari" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Nmae" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
